#!/usr/bin/env sh

enable_gui() {
    bind_rw "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR"

    set_env XDG_RUNTIME_DIR "$XDG_RUNTIME_DIR"
    set_env WAYLAND_DISPLAY "$WAYLAND_DISPLAY"
    set_env XDG_SESSION_TYPE "$XDG_SESSION_TYPE"
    set_env DBUS_SESSION_BUS_ADDRESS "$DBUS_SESSION_BUS_ADDRESS"
    set_env DISPLAY "$DISPLAY"
}
