#!/usr/bin/env sh

set -eu

PROJECT_DIR="${1:-$PWD}"

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

. "$SCRIPT_DIR/lib/bootstrap.sh"

vscode_profile

launch \
    /etc/profiles/per-user/pynezz/bin/code \
    --verbose \
    --disable-extensions \
    /workspace
